// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtovehogbvdzelcyggtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0b3ZlaG9nYnZkemVsY3lnZ3R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTcxNTcsImV4cCI6MjA2MjM5MzE1N30.eWAMcvEQ34a6pQPvxrxKvoYASD_L3ZKGg013XlkUs_c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);